helmDefaults:
  createNamespace: true
  cleanupOnFail: true
  historyMax: 5
  #atomic: false
  #wait: true
  #waitForJobs: true

---

releases:
- name: "jobmonitor"
  chart: ./jobmonitor
  installed: true
  labels:
    role: monitor
  secrets:
  - ./config-enc.yaml